# Custom Language File for Launcher Customizer

[ejs.app]
title = "OmegaMC Launcher"

[ejs.landing]
mediaGitHubURL = "https://www.omegamc.it"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.omegamc.it"

[ejs.settings]
sourceGithubLink = "https://discord.omegamc.it"
supportLink = "https://discord.omegamc.it"

[ejs.welcome]
welcomeHeader = "BENVENUTO/A SU OMEGAMC"
welcomeDescription = ""
welcomeDescCTA = "Copyright Â© 2026 OmegaMC Studios"
